version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/default-prod.conf:/etc/nginx/conf.d/default-prod.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./docker/php-fpm/logs:/var/log/php-fpm
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3366:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network
volumes:
  mysqldata:

networks:
  app-network:
    driver: bridge